package performance

import (
	"math"
	"time"
)

// round2 rounds to two decimals, matching the precision used across the app for
// index and percentage figures.
func round2(v float64) float64 { return math.Round(v*100) / 100 }

// isFinite reports whether v is a usable (non-NaN, non-Inf) number.
func isFinite(v float64) bool { return !math.IsNaN(v) && !math.IsInf(v, 0) }

// CurrentIndex returns the live ranked index for a state given the current
// base-currency portfolio value. A paused state (or a state with no valid
// segment) reports its preserved checkpoint index unchanged — an empty portfolio
// never divides by zero and never drifts.
func CurrentIndex(state State, currentValueBase float64) float64 {
	if state.Status != StatusActive || state.SegmentStartValueBase == nil || *state.SegmentStartValueBase <= 0 {
		return state.CheckpointIndex
	}
	return state.CheckpointIndex * currentValueBase / *state.SegmentStartValueBase
}

// indexBeforeMutation computes the ranked index just before a mutation, from the
// pre-mutation value. For an active portfolio this is the live index; for a
// paused one it is the preserved checkpoint (the empty portfolio had no value).
func indexBeforeMutation(state State, in CheckpointInput) float64 {
	if state.Status == StatusActive && state.SegmentStartValueBase != nil && *state.SegmentStartValueBase > 0 && in.HasActiveBefore {
		return state.CheckpointIndex * in.ValueBeforeBase / *state.SegmentStartValueBase
	}
	return state.CheckpointIndex
}

// activate builds the initial ranked state for a portfolio that is entering the
// ranked-tracking model for the first time. A non-empty portfolio starts at
// index 100 with its current value as the first segment start; an empty one
// starts paused at index 100 with no segment.
func activate(portfolioID, userID string, valueBase float64, hasActive bool, at time.Time) State {
	st := State{
		PortfolioID:       portfolioID,
		UserID:            userID,
		CheckpointIndex:   100,
		TrackingStartedAt: at,
		UpdatedAt:         at,
		Version:           1,
	}
	if hasActive {
		v := valueBase
		st.Status = StatusActive
		st.SegmentStartValueBase = &v
		st.SegmentStartedAt = &at
	} else {
		st.Status = StatusPaused
		st.SegmentStartValueBase = nil
	}
	return st
}

// applyCheckpoint returns the new state produced by a mutation. The invariant it
// enforces: the ranked index is identical immediately before and immediately
// after the mutation (zero return generated by the mutation itself). Only later
// market/FX movement, relative to the NEW segment start value, can move it.
//
//	index_before = checkpoint * value_before / segment_start   (active)
//	new checkpoint = index_before
//	new segment_start = value_after                            (active after)
//	new status = active if the portfolio still holds positions, else paused
//
// A paused → active transition resumes from the preserved checkpoint index
// rather than resetting to 100.
func applyCheckpoint(prev State, in CheckpointInput) State {
	index := indexBeforeMutation(prev, in)

	next := prev
	next.UpdatedAt = in.At
	next.CheckpointIndex = index
	next.Version = prev.Version + 1
	if in.HasActiveAfter {
		v := in.ValueAfterBase
		next.Status = StatusActive
		next.SegmentStartValueBase = &v
		startedAt := in.At
		next.SegmentStartedAt = &startedAt
	} else {
		next.Status = StatusPaused
		next.SegmentStartValueBase = nil
	}
	return next
}
