/**
 * Centralized query keys. Position changes ripple into performance ranking and
 * badges, so mutations invalidate all four of these.
 */
export const queryKeys = {
  activity: {
    all: ["activity"] as const,
    list: (params: object = {}) => ["activity", "list", params] as const,
    detail: (id: string) => ["activity", "detail", id] as const,
  },
  portfolio: {
    all: ["portfolio"] as const,
    summary: ["portfolio", "summary"] as const,
    positions: ["portfolio", "positions"] as const,
    position: (id: string) => ["portfolio", "position", id] as const,
    closedPositions: ["portfolio", "closedPositions"] as const,
    closedPosition: (id: string) => ["portfolio", "closedPosition", id] as const,
    cash: ["portfolio", "cash"] as const,
    allocation: ["portfolio", "allocation"] as const,
    sellPreview: (positionId: string, quantity: number, price: number, fee: number) =>
      ["portfolio", "sellPreview", positionId, quantity, price, fee] as const,
  },
  performance: {
    all: ["performance"] as const,
    history: (timeframe: string) => ["performance", "history", timeframe] as const,
    attribution: ["performance", "attribution"] as const,
    benchmarks: ["performance", "benchmarks"] as const,
    achievements: ["performance", "achievements"] as const,
    leaderboardStanding: ["performance", "leaderboardStanding"] as const,
  },
  positions: ["positions"] as const,
  closedPositions: ["positions", "closed"] as const,
  portfolioSummary: ["portfolioSummary"] as const,
  cash: ["portfolioCash"] as const,
  activities: ["portfolioActivities"] as const,
  corporateActions: ["portfolioCorporateActions"] as const,
  incomeEvents: ["portfolioIncomeEvents"] as const,
  leaderboard: ["leaderboard"] as const,
  dashboardLeaderboard: ["leaderboard", "dashboard"] as const,
  leaderboardMe: ["leaderboardMe"] as const,
  leaderboardStanding: (timeframe: string) => ["leaderboardMe", timeframe] as const,
  achievements: ["achievements"] as const,
  competitions: ["competitions"] as const,
  currentSprintStatus: (id: string) => ["currentSprintStatus", id] as const,
  sprintLeaderboard: (id: string) => ["sprintLeaderboard", id] as const,
  myProfile: ["profile", "me"] as const,
  publicProfile: (handle: string) => ["profile", handle] as const,
  exploreProfiles: (params: object) => ["exploreProfiles", params] as const,
  instrumentSearch: (q: string) => ["instruments", "search", q] as const,
  quotes: (symbols: string[]) => ["quotes", symbols] as const,
  followState: (handle: string) => ["social", "followState", handle] as const,
  friends: ["social", "friends"] as const,
  following: ["social", "following"] as const,
  followers: ["social", "followers"] as const,
  dmConversations: ["dm", "conversations"] as const,
  dmMessages: (conversationId: string) => ["dm", "messages", conversationId] as const,
};

/** Queries to invalidate after any successful position mutation. */
export const POSITION_MUTATION_INVALIDATIONS = [
  queryKeys.activity.all,
  queryKeys.portfolio.all,
  queryKeys.performance.all,
  queryKeys.positions,
  queryKeys.closedPositions,
  queryKeys.portfolioSummary,
  queryKeys.cash,
  queryKeys.activities,
  queryKeys.corporateActions,
  queryKeys.incomeEvents,
  queryKeys.leaderboard,
  queryKeys.leaderboardMe,
  queryKeys.achievements,
  queryKeys.myProfile,
] as const;
